config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  #get 'home/index'
  get 'home/about'
  #root 'home#index'
  root 'friends#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correctUser,only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend=current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correctUser
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized To Edit This Friend" if @friend.nil?
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :instagram, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>

<div class="field form-group">
    <% form.label :first_name %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone Number" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :instagram, class:"form-control", placeholder:"Instagram" %>
  </div>

  <div class="field form-group">
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>
 
  
  
<br/>
  <div class="actions">
    <%= form.submit class:'btn btn-primary' %>
  </div>

<% end %>

app/views/friends/edit.html.erb
<h1>Edit Friend</h1>

<%= render 'form', friend: @friend %><br/>

<%= link_to 'Show', @friend , class:"btn btn-primary"%> 
<%= link_to 'Destroy', @friend, method: :delete, data: { confirm: 'Are you sure?' },
                  class:"btn btn-danger"%>
<%= link_to 'Back', friends_path ,class:"btn btn-secondary"%>

app/views/friends/index.html.erb
<% if user_signed_in? %>
  <h1>Friends</h1>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Phone</th>
          <th>Instagram</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @friends.each do |friend| %>
            <% if friend.user == current_user%>
              <tr>
                <td><%= link_to friend.first_name+ ' ' + friend.last_name, friend %></td>
                <td><%= friend.email %></td>
                <td><%= friend.phone %></td>
                <td><%= friend.instagram %></td>
                <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' },
                  class:"btn btn-danger"%></td>
                
              </tr>
            <% end%>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'Add New ', new_friend_path, class:"btn btn-primary" %>

<% else%>
<img src="https://i.pinimg.com/originals/91/c5/e0/91c5e026b5b1d847772e5225531aaa0a.jpg" class="img-fluid" alt="Responsive image">
<h1 class="title">A place to save your friend</h1>
<img src="https://i.pinimg.com/originals/9e/c3/6f/9ec36fd83fe98dc75a1038e14569e9d2.jpg" class="img-fluid" alt="Responsive image">

<% end%>

app/views/friends/new.html.erb
<h1>New Friend</h1>

<%= render 'form', friend: @friend %><br>

<%= link_to 'Back to Home', friends_path ,class:"btn btn-secondary"%>

app/views/friends/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<h1>Friend Detail</h1>
<br>

<div class="jumbotron">
  <h1 class="display-4"><%= @friend.first_name %> <%= @friend.last_name %></h1>
  <p class="lead"><strong>Email:</strong> <%= @friend.email %></p>
  <hr class="my-4">
  <p><strong>Phone:</strong> <%= @friend.phone %></p>
  <p><strong>Instagram:</strong> <%= @friend.instagram %></p><br>
 <%= link_to 'Edit User', edit_friend_path(@friend), class:"btn btn-primary" %> 
 <%= link_to 'Back to Home', friends_path, class:"btn btn-secondary" %>
</div>

app/views/home/_footer.html.erb
    <footer>
        <div class="container">
            <div class="footer-content">
            

            </div>
            <hr>
            <p class="end">Nguyen Minh Hieu</p>
            <div class="footer-icon-link"
                <a href="https://www.facebook.com/hieuNguyen292/" class="footer-icon"><i class="fab fa-facebook-f"></i></a>
                <a href="https://github.com/hieunm292" class="footer-icon"><i class="fab fa-github-alt"></i></a>
            </div>
            
        </div>
    </footer>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <%= link_to 'Friend App', root_path, class:"navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
     
      
     

      <% if user_signed_in? %>
      
        <li class="nav-item">
          <%= link_to 'Add Friend', new_friend_path, class:"nav-link" %> 
        </li>
        
        <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
        </li>

      <% else %>

        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
        </li>

      <% end %>

    </ul>
    <form class="form-inline my-2 my-lg-0">
     
    </form>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Hello World</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="https://i.pinimg.com/originals/60/61/32/6061327ebb3155a40796e0e74f55a813.png" sizes="20x20">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

    <title>Friend App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header' %>

    <div class="container" style="margin-top: 20px">
    <br/>
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
    
      <%= yield %>
    </div>
    <%= render 'home/footer' %>

  
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>